ALTER TABLE raex_dict ADD COLUMN inn character varying;
ALTER TABLE raex_dict ADD COLUMN qs character varying;

TRUNCATE TABLE raex_dict;

INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('1', 'Московский государственный университет имени М.В. Ломоносова', '7729082090', '74');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('2', 'Московский физико-технический институт (национальный исследовательский университет)', '5008006211', '281');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('3', 'Национальный исследовательский ядерный университет "МИФИ"', '7724068140', '314');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('4', 'Санкт-Петербургский государственный университет', '7801002274', '225');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('5', 'Национальный исследовательский университет "Высшая школа экономики"', '7714030726', '298');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('6', 'Московский государственный технический университет имени Н.Э. Баумана (национальный исследовательский университет)', '7701002520', '282');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('7', 'МГИМО МИД России', '7729134728', '348');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('8', 'Национальный исследовательский Томский политехнический университет', '7018007264', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('9', 'Санкт-Петербургский политехнический университет Петра Великого', '7804040077', '401');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('10', 'Российская академия народного хозяйства и государственной службы при Президенте РФ', '7729050901', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('11', 'Новосибирский национальный исследовательский государственный университет', '5408106490', '228');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('12', 'Уральский федеральный университет имени первого Президента России Б.Н. Ельцина', '6660003190', '331');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('13', 'Финансовый университет при Правительстве РФ', '7701359513', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('14', 'Университет ИТМО', '7813045547', '360');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('15', 'Российский экономический университет имени Г.В. Плеханова', '7705043493', '751');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('16', 'Национальный исследовательский технологический университет «МИСиС»', '7706019535', '428');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('17', 'Национальный исследовательский Томский государственный университет', '7018012970', '401');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('18', 'Первый Московский государственный медицинский университет имени И.М. Сеченова Минздрава России', '7704047505', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('19', 'Российский университет дружбы народов', '7728073720', '326');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('20', 'Казанский (Приволжский) федеральный университет', '1655018018', '370');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('21', 'Московский авиационный институт (национальный исследовательский университет)', '7712038455', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('22', 'Российский национальный исследовательский медицинский университет имени Н.И. Пирогова Минздрава России', '7728095113', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('23', 'Сибирский федеральный университет', '2463011853', '1001');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('24', 'Национальный исследовательский университет "МЭИ"', '7722019652', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('25', 'Дальневосточный федеральный университет', '2536014538', '493');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('26', 'Российский государственный университет нефти и газа (национальный исследовательский университет) имени И.М. Губкина', '7736093127', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('27', 'Первый Санкт-Петербургский государственный медицинский университет имени академика И.П. Павлова Минздрава России', '7813047463', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('28', 'Южный федеральный университет', '6163027810', '591');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('29', 'Всероссийская академия внешней торговли Министерства экономического развития РФ', '7729071387', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('30', 'Московский государственный лингвистический университет', '7704024466', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('31', 'Национальный исследовательский Нижегородский государственный университет имени Н.И. Лобачевского', '5262004442', '601');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('32', 'Московский государственный юридический университет имени О.Е. Кутафина (МГЮА)', '7703013574', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('33', 'Санкт-Петербургский горный университет', '7801021076', '1001');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('34', 'Национальный исследовательский Московский государственный строительный университет', '7716103391', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('35', 'Московский педагогический государственный университет', '7704077771', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('36', 'Санкт-Петербургский государственный экономический университет', '7840483155', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('37', 'Российский государственный педагогический университет имени А. И. Герцена', '7808027849', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('38', 'Белгородский государственный национальный исследовательский университет', '3123035312', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('39', 'Санкт-Петербургский государственный электротехнический университет "ЛЭТИ" имени В.И. Ульянова (Ленина)', '7813045402', '701');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('40', 'Северо-Восточный федеральный университет имени М.К. Аммосова', '1435037142', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('41', 'Казанский государственный медицинский университет Минздрава России', '1655007760', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('42', 'Новосибирский государственный технический университет', '5404105174', '801');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('43', 'Казанский национальный исследовательский технический университет имени А.Н. Туполева-КАИ', '1654003114', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('44', 'Московский государственный медико-стоматологический университет имени А.И. Евдокимова Минздрава России', '7707082145', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('45', 'Воронежский государственный университет', '3666029505', '1001');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('46', 'Самарский национальный исследовательский университет имени академика С.П. Королёва', '6316000632', '591');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('47', 'Российский химико-технологический университет имени Д.И. Менделеева', '7707072637', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('48', 'Российский государственный гуманитарный университет', '7707033405', '1001');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('49', 'Алтайский государственный университет', '2225004738', '571');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('50', 'Самарский государственный медицинский университет Минздрава России', '6317002858', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('51', 'Санкт-Петербургский государственный архитектурно-строительный университет', '7809011023', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('52', 'МИРЭА - Российский технологический университет', '7729040491', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('53', 'Пермский национальный исследовательский политехнический университет', '5902291029', '801');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('54', 'Московский государственный технологический университет "СТАНКИН"', '7707003506', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('55', 'Уфимский государственный нефтяной технический университет', '277006179', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('56', 'Российский государственный аграрный университет – МСХА имени К.А. Тимирязева', '7713080682', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('57', 'Сибирский государственный медицинский университет Минздрава России', '7018013613', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('58', 'Белгородский государственный технологический университет имени В.Г. Шухова', '3123017793', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('59', 'Ставропольский государственный аграрный университет', '2634003069', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('60', 'Томский государственный университет систем управления и радиоэлектроники (ТУСУР)', '7021000043', '250');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('61', 'Южно-Уральский государственный университет (национальный исследовательский университет)', '7453019764', '801');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('62', 'Государственный университет "Дубна"', '5010010374', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('63', 'Южно-Российский государственный политехнический университет (НПИ) имени М.И. Платова', '6150010834', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('64', 'Северо-Западный государственный медицинский университет имени И.И. Мечникова Министерства здравоохранения РФ', '7842461679', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('65', 'Московский государственный областной университет', '7709123968', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('66', 'Санкт-Петербургский государственный педиатрический медицинский университет Минздрава России', '7802010020', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('67', 'Самарский государственный технический университет', '6315800040', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('68', 'Курский государственный медицинский университет Министерства здравоохранения РФ', '4629027572', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('69', 'Московский городской педагогический университет', '7717043346', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('70', 'Национальный исследовательский университет «МИЭТ»', '7735041133', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('71', 'Технологический университет имени дважды Героя Советского Союза, летчика-космонавта А.А. Леонова', '5018051823', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('72', 'Петрозаводский государственный университет', '1001040287', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('73', 'Донской государственный технический университет', '6165033136', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('74', 'Северо-Кавказский федеральный университет', '2635014955', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('75', 'Тюменский государственный университет', '7202010861', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('76', 'Волгоградский государственный университет', '3446500743', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('77', 'Балтийский федеральный университет имени Иммануила Канта', '3906019856', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('78', 'Томский государственный архитектурно-строительный университет', '7020000080', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('79', 'Рязанский государственный медицинский университет имени академика И.П. Павлова Министерства здравоохранения РФ', '6228013199', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('80', 'Воронежский государственный медицинский университет имени Н.Н. Бурденко Минздрава России', '3666027794', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('81', 'Саратовский национальный исследовательский государственный университет имени Н.Г. Чернышевского', '6452022089', '521');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('82', 'Национальный исследовательский Мордовский государственный университет имени Н.П. Огарёва', '1326043499', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('83', 'Казанский национальный исследовательский технологический университет', '1655018804', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('84', 'Уральский государственный медицинский университет Министерства здравоохранения РФ', '6658017389', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('85', 'Государственный университет управления', '7721037218', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('86', 'Северный (Арктический) федеральный университет имени М.В. Ломоносова', '2901039102', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('87', 'Курский государственный университет', '4629031018', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('88', 'Государственный гуманитарно-технологический университет', '5034082850', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('89', 'Тюменский индустриальный университет', '7202028202', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('90', 'Кабардино-Балкарский государственный университет имени Х.М. Бербекова', '711037537', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('91', 'Башкирский государственный медицинский университет Минздрава России', '0274023088', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('92', 'Государственный социально-гуманитарный университет', '5022014285', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('93', 'Волгоградский государственный технический университет', '3444049170', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('94', 'Воронежский государственный технический университет', '3662020886', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('95', 'Тюменский государственный медицинский университет Минздрава России', '7203001010', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('96', 'Тихоокеанский государственный университет', '2725006620', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('97', 'Российский новый университет (РосНОУ)', '7709469701', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('98', 'Юго-Западный государственный университет', '4629029058', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('99', 'Московский политехнический университет', '7719455553', '');
INSERT INTO raex_dict(position, full_name, inn, qs) VALUES('100', 'Алтайский государственный технический университет имени И.И. Ползунова', '2224017710', '');
