TRUNCATE TABLE region;
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Ростовская область','1.svg','Rostov');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Республика Ингушетия','2.svg','Ingush');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Архангельская область','3.svg','Arkhangel''sk');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Чеченская республика','4.svg','Chechnya');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Оренбургская область','5.svg','Orenburg');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Сахалинская область','6.svg','Sakhalin');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Орловская область','7.svg','Orel');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Республика Марий Эл','8.svg','Mariy-El');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Карачаево-Черкесская республика','9.svg','Karachay-Cherkess');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Севастополь','10.svg','Sevastopol''');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Республика Башкортостан','11.svg','Bashkortostan');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Костромская область','12.svg','Kostroma');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Самарская область','13.svg','Samara');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Чувашская республика','14.svg','Chuvash');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Липецкая область','15.svg','Lipetsk');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Алтайский край','16.svg','Altay');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Республика Дагестан','17.svg','Dagestan');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Белгородская область','18.svg','Belgorod');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Кабардино-Балкарская республика','19.svg','Kabardin-Balkar');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Воронежская область','20.svg','Voronezh');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Челябинская область','21.svg','Chelyabinsk');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Камчатский край','22.svg','Kamchatka');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Кемеровская область','23.svg','Kemerovo');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Республика Татарстан','24.svg','Tatarstan');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Омская область','25.svg','Omsk');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Краснодарский край','26.svg','Krasnodar');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Новгородская область','27.svg','Novgorod');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Удмуртская республика','28.svg','Udmurt');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Приморский край','29.svg','Primor''ye');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Республика Саха (Якутия)','30.svg','Sakha');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Тюменская область','31.svg','Tyumen');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Республика Алтай','32.svg','Gorno-Altay');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Рязанская область','33.svg','Ryazan''');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Байконур','34.svg','');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Магаданская область','35.svg','Maga Buryatdan');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Республика Коми','36.svg','Komi');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Смоленская область','37.svg','Smolensk');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Республика Хакасия','38.svg','Khakass');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Хабаровский край','39.svg','Khabarovsk');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Свердловская область','40.svg','Sverdlovsk');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Пензенская область','41.svg','Penza');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Ямало-Ненецкий автономный округ','42.svg','Yamal-Nenets');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Владимирская область','43.svg','Vladimir');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Ненецкий автономный округ','44.svg','Nenets');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Чукотский автономный округ','45.svg','Chukot');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Новосибирская область','46.svg','Novosibirsk');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Республика Тыва','47.svg','Tuva');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Тульская область','48.svg','Tula');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Брянская область','49.svg','Bryansk');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Кировская область','50.svg','Kirov');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Республика Бурятия','51.svg','Buryat');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Ставропольский край','52.svg','Stavropol''');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Ярославская область','53.svg','Yaroslavl''');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Ивановская область','54.svg','Ivanovo');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Ленинградская область','55.svg','Leningrad');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Нижегородская область','56.svg','Nizhegorod');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Республика Адыгея','57.svg','Adygey');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Томская область','58.png','Tomsk');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Республика Калмыкия','59.svg','Kalmyk');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Республика Крым','60.svg','Crimea');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Республика Северная Осетия - Алания','61.svg','North Ossetia');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Красноярский край','62.svg','Krasnoyarsk');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Пермский край','63.svg','Perm''');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Ханты-Мансийский автономный округ - Югра','64.svg','Khanty-Mansiy');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Астраханская область','65.svg','Astrakhan''');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Республика Карелия','66.svg','Karelia');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Калининградская область','67.svg','Kaliningrad');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Тверская область','68.svg','Tver''');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Псковская область','69.svg','Pskov');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Амурская область','70.svg','Amur');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Саратовская область','71.svg','Saratov');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Тамбовская область','72.svg','Tambov');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Волгоградская область','73.svg','Volgograd');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Вологодская область','74.svg','Vologda');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Москва','75.svg','Moscow City');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Санкт-Петербург','76.svg','City of St. Petersburg');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Республика Мордовия','77.svg','Mordovia');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Курганская область','78.svg','Kurgan');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Еврейская автономная область','79.svg','Yevrey');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Мурманская область','80.svg','Murmansk');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Забайкальский край','81.svg','Zabaikalskiy Krai');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Калужская область','82.svg','Kaluga');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Иркутская область','83.svg','Irkutsk');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Ульяновская область','84.svg','Ul''yanovsk');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Курская область','85.svg','Kursk');
INSERT INTO region (name_ru, path_image, name_eng) VALUES ('Московская область','86.svg','Moskva');
